#!/bin/bash

set -e

results="$(pwd)/results/ffmpeg-results.txt"
ffmpegurl='http://ffmpeg.org/releases/ffmpeg-3.0.2.tar.bz2'
ffmpegfile='ffmpeg-3.0.2.tar.bz2'
inputfileurl='http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_stereo.avi'
localdir='ffmpeg-3.0.2'
pathdir="$(pwd)/.env/lib/hardening-wrapper/bin"
JOBS=$(nproc||echo 1)

if [ ! -f "$ffmpegfile" ]
    then
        echo -e "Downloading ffmpeg source files..."
        curl -O "$ffmpegurl"
    else
        echo -e "ffmpeg already downloaded. Continuing..."
fi

if [ ! -d "$localdir" ]
    then
        tar -xvf "$ffmpegfile"
    else
        echo -e "ffmpeg alreday extracted. Continuing..."
fi

if [ ! -d "$pathdir" ]
    then
		echo -e "ERROR: pathdir does not exist, try 'make setup'"
		exit 1
fi


cd "$localdir"

CONFIGURE_OPTIONS="--prefix='/usr'
    --disable-debug
    --disable-static
    --disable-stripping
    --enable-avisynth
    --enable-avresample
    --enable-fontconfig
    --enable-gnutls
    --enable-gpl
    --enable-ladspa
    --enable-libass
    --enable-libbluray
    --enable-libdcadec
    --enable-libfreetype
    --enable-libfribidi
    --enable-libgsm
    --enable-libiec61883
    --enable-libmodplug
    --enable-libmp3lame
    --enable-libopencore_amrnb
    --enable-libopencore_amrwb
    --enable-libopenjpeg
    --enable-libopus
    --enable-libpulse
    --enable-libschroedinger
    --enable-libsoxr
    --enable-libspeex
    --enable-libssh
    --enable-libtheora
    --enable-libv4l2
    --enable-libvidstab
    --enable-libvorbis
    --enable-libvpx
    --enable-libwebp
    --enable-libx264
    --enable-libx265
    --enable-libxvid
    --enable-netcdf
    --enable-shared
    --enable-version3
    --enable-x11grab"

curl -o input.avi "$inputfileurl"

if [ -z "$1" ] || [ "1" == "$1" ]; then
	echo -e "Compiling with -fstack-protector-strong and partial relro"
	LDFLAGS='-Wl,-O1,--sort-common,--as-needed,-z,relro' \
		CFLAGS='-fstack-protector-strong -pipe -O2' \
		CXXFLAGS='-fstack-protector-strong -pipe -O2' \
		CPPFLAGS='-D_FORTIFY_SOURCE=2' \
		./configure ${CONFIGURE_OPTIONS}
	make clean
	make -j${JOBS}
	echo -e "Compilation finished, running test 1"
	./ffmpeg -benchmark -i input.avi -f null - |& tee $results
	echo -e "Test 1 completed."
fi


if [ -z "$1" ] || [ "2" == "$1" ]; then
	echo -e "Compiling with -fstack-protector-strong, partial relro, and -fstack-check"
	LDFLAGS='-Wl,-O1,--sort-common,--as-needed,-z,relro' \
		CFLAGS='-fstack-protector-strong -fstack-check -pipe -O2' \
		CXXFLAGS='-fstack-protector-strong -fstack-check -pipe -O2' \
		CPPFLAGS='-D_FORTIFY_SOURCE=2' \
		./configure ${CONFIGURE_OPTIONS}
	make clean
	make -j${JOBS}
	echo -e "Compilation finished, running test 2"
	./ffmpeg -benchmark -i input.avi -f null - |& tee -a $results
	echo -e "Test 2 completed."
fi


if [ -z "$1" ] || [ "3" == "$1" ]; then
	echo -e "Compiling with -fstack-protector-strong, partial relro, and PIE"
	LDFLAGS='-Wl,-O1,--sort-common,--as-needed,-z,relro' \
		CFLAGS='-fstack-protector-strong -pipe -O2 -fno-stack-check' \
		CXXFLAGS='-fstack-protector-strong -pipe -O2 -fno-stack-check' \
		CPPFLAGS='-D_FORTIFY_SOURCE=2' \
		./configure ${CONFIGURE_OPTIONS}
	make clean
	PATH="${pathdir}:${PATH}" HARDENING_BINDNOW=0 make -j${JOBS}
	echo -e "Compilation finished, running test 3"
	./ffmpeg -benchmark -i input.avi -f null - |& tee -a $results
	echo -e "Test 3 completed."
fi


if [ -z "$1" ] || [ "4" == "$1" ]; then
	echo -e "Compiling with -fstack-protector-strong, partial relro, PIE, and -fstack-check"
	LDFLAGS='-Wl,-O1,--sort-common,--as-needed,-z,relro' \
		CFLAGS='-fstack-protector-strong -fstack-check -pipe -O2' \
		CXXFLAGS='-fstack-protector-strong -fstack-check -pipe -O2' \
		CPPFLAGS='-D_FORTIFY_SOURCE=2' \
		./configure ${CONFIGURE_OPTIONS}
	make clean
	PATH="${pathdir}:${PATH}" HARDENING_BINDNOW=0 make -j${JOBS}
	echo -e "Compilation finished, running test 4"
	./ffmpeg -benchmark -i input.avi -f null - |& tee -a $results
	echo -e "Test 4 completed."
fi


if [ -z "$1" ] || [ "5" == "$1" ]; then
	echo -e "Compiling with -fstack-protector-strong, full relro, PIE"
	LDFLAGS='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now' \
		CFLAGS='-fstack-protector-strong -pipe -O2 -fno-stack-check' \
		CXXFLAGS='-fstack-protector-strong -pipe -O2 -fno-stack-check' \
		CPPFLAGS='-D_FORTIFY_SOURCE=2' \
		./configure ${CONFIGURE_OPTIONS}
	make clean
	PATH="${pathdir}:${PATH}" make -j${JOBS}
	echo -e "Compilation finished, running test 5"
	./ffmpeg -benchmark -i input.avi -f null - |& tee -a $results
	echo -e "Test 5 completed."
fi


if [ -z "$1" ] || [ "6" == "$1" ]; then
	echo -e "Compiling with -fstack-protector-strong, full relro, PIE, -fstack-check"
	LDFLAGS='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now' \
		CFLAGS='-fstack-protector-strong -fstack-check -pipe -O2' \
		CXXFLAGS='-fstack-protector-strong -fstack-check -pipe -O2' \
		CPPFLAGS='-D_FORTIFY_SOURCE=2' \
		./configure ${CONFIGURE_OPTIONS}
	make clean
	PATH="${pathdir}:${PATH}" make -j${JOBS}
	echo -e "Compilation finished, running test 6"
	./ffmpeg -benchmark -i input.avi -f null - |& tee -a $results
	echo -e "Test 6 completed."
fi


if [ -z "$1" ] || [ "7" == "$1" ]; then
	echo -e "Compiling with -fstack-protector-strong, full relro, PIE, -fno-plt"
	LDFLAGS='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now' \
		CFLAGS='-fstack-protector-strong -fno-plt -pipe -O2 -fno-stack-check' \
		CXXFLAGS='-fstack-protector-strong -fno-plt -pipe -O2 -fno-stack-check' \
		CPPFLAGS='-D_FORTIFY_SOURCE=2' \
		./configure ${CONFIGURE_OPTIONS}
	make clean
	PATH="${pathdir}:${PATH}" make -j${JOBS}
	echo -e "Compilation finished, running test 7"
	./ffmpeg -benchmark -i input.avi -f null - |& tee -a $results
	echo -e "Test 7 completed."
fi


if [ -z "$1" ] || [ "8" == "$1" ]; then
	echo -e "Compiling with -fstack-protector-strong, full relro, PIE, -fno-plt, and -fstack-check"
	LDFLAGS='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now' \
		CFLAGS='-fstack-protector-strong -fno-plt -fstack-check -pipe -O2' \
		CXXFLAGS='-fstack-protector-strong -fno-plt -fstack-check -pipe -O2' \
		CPPFLAGS='-D_FORTIFY_SOURCE=2' \
		./configure ${CONFIGURE_OPTIONS}
	make clean
	PATH="${pathdir}:${PATH}" make -j${JOBS}
	echo -e "Compilation finished, running test 8"
	./ffmpeg -benchmark -i input.avi -f null - |& tee -a $results
	echo -e "Test 8 completed."
fi
